### ISSUE TITLE
Test split

### ISSUE THREAD

**Issue by sharifinjf** [neeharperi/FutureDet#12]
Hi
Thank you for sharing the source code.
 I tried to get results on the test split, but I could not. Is it any straightforward solution?

**Comment by neeharperi** [comment]
It is not possible to get results on the test split since nuScenes does not release test annotations. We present results on the validation set.

**Comment by sharifinjf** [comment]
> It is not possible to get results on the test split since nuScenes does not release test annotations. We present results on the validation set.

ok, I do want not to calculate the metrics. I need to visualize the result of the test split.

**Comment by neeharperi** [comment]
I don't think there is a straightforward way to run on the test split. Can you share what you've tried, any error traces, and I can try to help guide you.

**Comment by sharifinjf** [comment]
how can I run dis_test.py on test split, there are arguments for this task. But I can't do data preparation for the test split since its annotations are not available.
