### ISSUE TITLE
res["lidar"]["bev_map"] : axes dont match array

### ISSUE THREAD

**Issue by woshichase** [neeharperi/FutureDet#2]
Hi,  Thank you so much for contributing such a great work.

I followed your installation step and data generating step. 

The process seems to be plain sailing:
![image](https://user-images.githubusercontent.com/20211463/167788987-ea85e98a-a3a9-4980-aaf0-b9b740fed065.png)

However, when I changed the paths to my own and started to run, an error occurred:
![image](https://user-images.githubusercontent.com/20211463/167789536-57184076-8ac9-4190-84fb-f795abbd44c8.png)

Have you met the similar problem?

**Comment by neeharperi** [comment]
Thanks for your interest in our work!

I haven't seen this issue before. Could you give me a few more details about the exact script you're running so I can try to replicate the issue on my end? 

res["lidar"]["bev_map"] should be an empty numpy array of size (1, 180, 180). Can you check to verify the size of bev prior to the transpose operation?

**Comment by woshichase** [comment]
Hi，Thank you for your help.
It's the first training script in your README.
I checked the bev size. It is:
![Rz2k3yU5nT](https://user-images.githubusercontent.com/20211463/168112298-a955549d-511d-4a44-ae07-c6d931545510.jpg)
I am not sure which step turns this grey scale picture into two-channel style. Anyway I reshaped it to (1,180,180) and it turns well😊
