### ISSUE TITLE
Clues to solve ValueError: res["lidar"]["bev_map"] axes don't match array

### ISSUE THREAD

**Issue by MaxChanger** [neeharperi/FutureDet#3]
Hi, thanks for the great work. And I meet the same issue with [issue#2](https://github.com/neeharperi/FutureDet/issues/2), as following,
```bash
  File "~/Repo/FutureDet/det3d/datasets/pipelines/preprocess.py", line 221, in __call__
    res["lidar"]["bev_map"] = bev.transpose(2, 0, 1)
ValueError: axes don't match array
```
Although I use the v1.0-mini nuscenes data, I don't think it matters.
After my debugging, I found that the problem lies in the bev process of generating `info_xxx.pkl`, as follows

https://github.com/neeharperi/FutureDet/blob/960115e2d11e40c569c4fb9abc1f0e066e4a07b1/det3d/datasets/nuscenes/nusc_common.py#L508-L509
https://github.com/neeharperi/FutureDet/blob/960115e2d11e40c569c4fb9abc1f0e066e4a07b1/det3d/datasets/nuscenes/nusc_common.py#L544

The BEV image is loaded from the sdk in your another repo [python-sdk/nuscenes/nuscenes.py#L837-L842](https://github.com/neeharperi/nuscenes-forecast/blob/300082bb4cb23df836c4fb7e3c9b0236e248d4f4/python-sdk/nuscenes/nuscenes.py#L837-L842)

But their dimensions are (h,w), such as `ego_map.shape: (900, 900)`, `bev.shape: (180, 180)`, so `bev.transpose(2, 0, 1)` is wrong operations for this.

Hope that can provide clues to solve the problem.

**Comment by YiiiMeng** [comment]
I also encounter this problem, and I try to uncomment the line 211 and 214 (just above the bug line) in the preprocess.py, and it works.

**Comment by MaxChanger** [comment]
Thanks @YiMengNB, in issue#2, the author said''res["lidar"]["bev_map"] should be an empty numpy array of size (1, 180, 180)'' .
So, I simply added a dimension to `bev` before this line, such as `bev = bev[None, :, :]`, it also work. The predicted output can be obtained normally.

But I'm not sure if this is completely correct and consistent with the original intent.

**Comment by chenkangyang** [comment]
> 

This is reasonable to get 6 channel bevmap
Cuz
```
if self.bev_map:
    self.bev_conv = nn.Sequential(
        nn.Conv2d(6, 16, kernel_size=3, padding=1, bias=True), nn.BatchNorm2d(16), nn.ReLU(inplace=True),
        nn.Conv2d(16, 32, kernel_size=3, padding=1, bias=True), nn.BatchNorm2d(32), nn.ReLU(inplace=True),
        nn.Conv2d(32, share_conv_channel, kernel_size=3, padding=1, bias=True), nn.BatchNorm2d(share_conv_channel), nn.ReLU(inplace=True),
    )
```
in [center_head.py](https://github.com/neeharperi/FutureDet/blob/main/det3d/models/bbox_heads/center_head.py)
