### ISSUE TITLE
Expect the re-implenmation in MMDetection3D

### ISSUE THREAD

**Issue by KeyuLi** [neeharperi/FutureDet#5]

**Comment by neeharperi** [comment]
Thanks for your interest in our work! I'm currently working on adding support for Argoverse 2 and porting this to MMDetection3D by the end of August. I'll keep you in the loop.

**Comment by hutslib** [comment]
Hi, thanks for your nice work and I'm interested in testing it. Is there any update for support av2 and MMDetection3D? @neeharperi
