### ISSUE TITLE
No such file or directory: 'models/FutureDetection/nusc_centerpoint_forecast_n3dtf_detection/metrics_summary.json'

### ISSUE THREAD

**Issue by Sunyyyy** [neeharperi/FutureDet#6]
EXM, I can't find the json config "metrics_summary.json" when I evaluate the det3d model.
I would appreciate it if you could provide the file additionally!
Thanks!!

**Comment by mengqingyu123** [comment]
I meet the same problem while performing evaluate.py, did you solve it?

**Comment by Sunyyyy** [comment]
已收到您的邮件！祝好~

**Comment by Sunyyyy** [comment]
> I meet the same problem while performing evaluate.py, did you solve it?

Nope, author didn't reply me yet TAT

**Comment by Sunyyyy** [comment]
> I meet the same problem while performing evaluate.py, did you solve it?
I got it !  You should make sure that your **nuScenes path, version and split** in "evaluate.py" are true. Then run the code and all files will be generated automatically.

**Comment by mengqingyu123** [comment]
@Sunyyyy Nice job! Can you share the specific code? I'm currently like this and still can't get it to work.
![image](https://user-images.githubusercontent.com/37166419/196074470-2ca29d2c-d4c2-4324-921b-f4104be9a911.png)

**Comment by Sunyyyy** [comment]
> @Sunyyyy Nice job! Can you share the specific code? I'm currently like this and still can't get it to work. ![image](https://user-images.githubusercontent.com/37166419/196074470-2ca29d2c-d4c2-4324-921b-f4104be9a911.png)

I use the v1.0-mini for it and the code will be like below
![image](https://user-images.githubusercontent.com/74486483/196121815-fc1ffbb7-121c-45b3-b179-9c918940c7bb.png)
Check out whether you have processed your nuScenes Datasets correctly.
![image](https://user-images.githubusercontent.com/74486483/196122384-822c71db-c743-40f6-8f72-76f38e76c454.png)

**Comment by mengqingyu123** [comment]
@Sunyyyy According to your tips, I have solved the problem, thank you very much!
